GRUPTREE
   'INJE'     'FIELD'  /
   'PROD'     'FIELD'  /
   'MANI-B2'     'PROD'  /
   'MANI-B1'     'PROD'  /
   'MANI-D1'     'PROD'  /
   'MANI-D2'     'PROD'  /
   'MANI-E1'     'PROD'  /
   'MANI-E2'     'PROD'  /
   'MANI-K1'     'MANI-B1'  /
   'MANI-K2'     'MANI-D2'  /
   'MANI-C'     'INJE'  /
   'MANI-F'     'INJE'  /
   'WI-GSEG'     'INJE'  /
   'B1-DUMMY'     'MANI-B1'  /
   'D2-DUMMY'     'MANI-D2'  /
/
